
stages:
  - deploy

deploy_job:
  stage: deploy
  script:
  - apk update && apk add git
  - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/react-frontend.git
  - git push -f heroku client:master
  only:
  - client